name: user_repository
description: This package handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
