name: pizza_repository
description: This package handles pizza orders 
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  flutter:
    sdk: flutter